global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'node-prometheus'
    static_configs:
      - targets: ['localhost:8080']

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"
